# baseURL: https://hugo-toha.github.io

languageCode: en-us
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
defaultContentLanguage: zh
languages:
  en:
    languageName: English
    weight: 2
    title: Urie's Homepage
    flag: "/images/england.svg"
  zh:
    languageName: 简体中文
    weight: 1
    title: 杨锐的个人主页
    flag: /images/china.svg

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 3
    endLevel: 6
    ordered: false
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    codeFences: true
    guessSyntax: true
    # lists a set of line numbers or line number ranges to be highlighted.
    hl_Lines: ""

    # Configure anchors on line numbers. Valid values are true or false;
    # anchorLineNos: true

    # Configure a prefix for the anchors on line numbers. Will be suffixed with -, 
    # so linking to the line number 1 with the option lineanchors=prefix adds the anchor prefix-1 to the page.
    # lineAnchors: "prefix"
    lineNoStart: 1
    # configure line numbers. Valid values are true, false, table, or inline.
    # false will turn off line numbers if it’s configured to be on in site config.
    # New in v0.60.0 table will give copy-and-paste friendly code blocks.
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    # style: xcode # https://xyproto.github.io/splash/docs/all.html
    tabWidth: 4

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  background: /images/background.jpg
  # GitHub repo URL of your site
  gitRepo: https://github.com/Urie96/blog

  # gitalk:
  #   clientId: 3963ddedeeb12de5a5e8
  #   clientSecret: 4c8d7b565e6df6816a4f58caf1e0e615d5f80fd3
  #   repo: CommentsOnly
  #   owner: Urie96
    

  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: true

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will default to the theme logos if not provided.
  logo:
    main: /images/blog.svg
    inverted: /images/blog.svg
    favicon: /images/blog.svg

# deployment:
#   targets:
#     name: "mydeployment"
#   matchers:
#     pattern: "^.+\\.(js|css|svg|ttf)$"
#     gzip: true

# minify:
#   disableCSS: false
#   disableHTML: false
#   disableJS: false
#   disableJSON: false
#   disableSVG: false
#   disableXML: false
#   minifyOutput: true
#   tdewolff:
#     css:
#       decimals: -1
#       keepCSS2: true
#     html:
#       keepConditionalComments: true
#       keepDefaultAttrVals: true
#       keepDocumentTags: true
#       keepEndTags: true
#       keepQuotes: false
#       keepWhitespace: false
#     js: {}
#     json: {}
#     svg:
#       decimals: -1
#     xml:
#       keepWhitespace: false